---

- hosts: all
  gather_facts: True
  become: True

# @see https://docs.hortonworks.com/HDPDocuments/Ambari-2.6.0.0/bk_ambari-installation/content/hdp_26_repositories.html
  vars:
    - hdp_release_version : '2.6.3.0'
    - ambari_release_version: '2.6.0.0'
    - hdputil_release_version : '1.1.0.21'

  roles:
    - role_under_test

  post_tasks:
    - name: Check Repo Versions
      shell: "yum repolist | grep -c '{{ item }}'"
      register: hdp_version
      failed_when: hdp_version.stdout != '1'
      changed_when: False
      when: ansible_os_family == 'RedHat'
      with_items: ['Ambari-2.6.0.0', 'HDP-2.6.3.0', 'HDP-UTILS-1.1.0.21']
      become: True

    - name: Check Package Versions
      shell: "apt-cache policy| grep -c '{{ item }}' "
      register: hdp_version
      failed_when: hdp_version.stdout == '0'
      changed_when: False
      when: ansible_os_family == 'Debian'
      with_items: ['2.6.0.0[/ ]*Ambari', '2.6.3.0[/ ]*HDP', 'HDP-UTILS-1.1.0.21']
      become: True
