---

- hosts: all
  gather_facts: True
  become: True  

  vars:
    - hdp_release_version : '2.6.0.3'
    - ambari_release_version: '2.5.0.3'
    - hdputil_release_version : '1.1.0.21'

  roles:
    - role_under_test

  post_tasks:
    - name: Check Repo Versions
      shell: "yum repolist | grep -c '{{ item }}'"
      register: hdp_version
      failed_when: hdp_version.stdout != '1'
      changed_when: False
      when: ansible_os_family == 'RedHat'
      with_items: ['Ambari-2.5.0.3', 'HDP-2.6.0.3', 'HDP-UTILS-1.1.0.21']
      become: True

    - name: Check Package Versions
      shell: "apt-cache policy| grep -c '{{ item }}' "
      register: hdp_version
      failed_when: hdp_version.stdout != '1'
      changed_when: False
      when: ansible_os_family == 'Debian'
      with_items: ['2.5.0.3 Ambari', '2.6.0.3 HDP', 'HDP-UTILS-1.1.0.21']
      become: True


